!!! DO NOT RELEASE !!!

diff --git a/modemlink b/modemlink
--- a/modemlink
+++ b/modemlink
@@ -6,11 +6,34 @@
 PATH="/bin:/sbin:/usr/bin:/usr/sbin"
 export PATH
 
-XDIALOG_HIGH_DIALOG_COMPAT=1
-export XDIALOG_HIGH_DIALOG_COMPAT
+# we need gettext (is loaded in ssft.sh or cloned...)
+if [ -f /usr/bin/gettext.sh ]; then
+	. /usr/bin/gettext.sh || exit 1
+else
+	exit 1
+fi
+#---------------------------------------------------------------------
+# we need root rights
+#---------------------------------------------------------------------
+SU_ME=$(type -p su-me)  || SU_ME="/usr/bin/su-me"
+if [ "$UID" -ne 0 ]; then
+	[ -x "$SU_ME" ] && exec "$SU_ME" "$0" "$@"
 
-# Get root
-[ "`id -u`" != "0" ] && exec su-me "$0" "$@"
+	echo "$(gettext "Error: You must be root to run this script!")"
+	exit 1
+fi
+
+TEXTDOMAIN="modemlink"
+export TEXTDOMAIN
+TEXTDOMAINDIR=/usr/share/locale
+export TEXTDOMAINDIR
+
+
+SSFTSH="$(which ssft.sh)"			|| SSFTSH="/usr/bin/ssft.sh"
+# initialize ssft
+. "$SSFTSH"
+[ -n "$SSFT_FRONTEND" ] ||  SSFT_FRONTEND="$(ssft_choose_frontend)"
+
 
 TMP="$(mktemp -p /tmp/ modemlink-XXXXXXXXXX)"
 
@@ -19,133 +42,86 @@ bailout () {
 	exit $1
 }
 
-DIALOG="dialog"
-[ -n "$DISPLAY" ] && [ -x /usr/bin/Xdialog ] && DIALOG="Xdialog"
 
 trap bailout 1 2 3 15
 
-# Language-dependent Messages
-case "$LANG" in
-	de*|at*|ch*)
-		TITLE1="Art der Verbindung"
-		MESSAGE1="Bitte die gewünschten Verbindungsart auswählen:"
-		SERIAL="Serielle Schnittstelle (z.B. Modem)"
-		WINMODEM="Nach nicht-unterstützten \"WinModems\" suchen"
-		SIR="Standard SIR (oder USB)"
-		USB="USB Schnittstelle (z.B. Modem)"
-		IRDA="Infrarot Schnittstelle (z.B. für Handy/PDA)"
-		BLUETOOTH="Bluetooth Funkadapter (z.B. für Handy/PDA)"
-		TITLE_DONGLES="IRDA Adapter-Typ"
-		MESSAGE_DONGLES="Bitte den verwendeten IRDA-Adaptertyp auswählen:"
-		TITLE_TEST="Adaptertest - Strg-C zum Beenden des Tests"
-		TITLE_SRVFAIL="FEHLER"
-		MESSAGE_SRVFAIL="Konnte Daemon für Gerät nicht starten. Wahrscheinlich wurde die falsche Schnittstelle ausgewählt." 
-		AUTOSEARCH="ALLE Schnittstellen scannen"
-		TITLE_BLUES="Bluetooth-Geräte"
-		MESSAGE_BLUES="Folgende Bluetooth-Geräte befinden sich in der Umgebung. Bitte eins auswählen:"
-		TITLE_PIN="PIN"
-		MESSAGE_PIN="Bitte geben Sie eine 4-stellige PIN zur Authentfizierung der Bluetooth-Geräte ein:"
-		TITLE_GAUGE="Device-Scan..."
-		TITLE_LINK="/dev/modem Link erzeugen..."
-		MESSAGE_LINK="Möchten Sie den Symlink /dev/modem auf das neu konfigurierte Gerät setzen? Dies ist notwendig, wenn Sie das Gerät z.B. als Modem für kppp oder GPRS benutzen möchten (beides im Knoppix-Menü \"Netzwerk Konfiguration\" zu finden).
 
-Verlinken von /dev/modem -> "
-		TITLE_RETRY="FEHLER"
-		MESSAGE_RETRY="Das scheint nicht geklappt zu haben. Noch einmal versuchen?"
-		TITLE_BTID="Keine Bluetooth Geräte in Reichweite"
-		MESSAGE_BTID="Auf die Sendeanfrage hat kein Bluetooth-Gerät geantwortet. Bitte geben Sie die Adresse eines entfernten Bluetooth-Gerätes ein."
-		;;
-	*)
-		TITLE1="Connection Type"
-		MESSAGE1="Please select type of connection:"
-		WINMODEM="Scan for unsupported \"WinModems\""
-		SERIAL="Serial connector (i.e. Modem)"
-		SIR="Standard SIR (or USB)"
-		USB="USB connector (i.e. Modem)"
-		IRDA="Infrared wireless device (i.e. cellphone/PDA)"
-		BLUETOOTH="Bluetooth wireless device (i.e. cellphone/PDA)"
-		TITLE_DONGLES="IRDA Adapter type"
-		MESSAGE_DONGLES="Please select type of IRDA adapter:"
-		TITLE_TEST="Testing adapter - Hit Ctrl-C to end test."
-		TITLE_SRVFAIL="ERROR"
-		MESSAGE_SRVFAIL="Failed to start device daemon. Probably the selected port is wrong."
-		AUTOSEARCH="scan ALL devices"
-		TITLE_BLUES="Bluetooth Devices"
-		MESSAGE_BLUES="These bluetooth devices exist nearby. Please select:"
-		TITLE_PIN="PIN"
-		MESSAGE_PIN="Please chose a 4-digit PIN number for authention of bluetooth devices:"
-		TITLE_GAUGE="Scanning devices..."
-		TITLE_LINK="Create /dev/modem link..."
-		MESSAGE_LINK="Do you want to set the symlink /dev/modem to point to the newly configured device? This is necessary if you want o use the device as modem for kppp, as an example, or for using GPRS (all of these located in the Knoppix \"network configuration\" menu).
-
-Create link /dev/modem -> "
-		TITLE_RETRY="ERROR"
-		MESSAGE_RETRY="This seems to have failed. Do you want to try again?"
-		TITLE_BTID="No bluetooth devices in range"
-		MESSAGE_BTID="No bluetooth devices responded to our scan. Please enter the address of a remote bluetooth device."
-		;;
-esac
 
 # Shortcut description selected
-TYPES=(serial "$SERIAL" on \
-usb "$USB" off \
-irda "$IRDA" off \
-bluetooth "$BLUETOOTH" off \
-winmodem "$WINMODEM" off)
+TYPES=(
+	"serial $(gettext "Serial connector (i.e. Modem)")" \
+	"usb $(gettext "USB connector (i.e. Modem)")" \
+	"irda $(gettext "Infrared wireless device (i.e. cellphone/PDA)")" \
+	"bluetooth $(gettext "Bluetooth wireless device (i.e. cellphone/PDA)")" \
+#	"winmodem $(gettext "Scan for unsupported \"WinModems\"")"
+)
 
 type scanmodem >/dev/null 2>&1 || { unset TYPES[14]; unset TYPES[13]; unset TYPES[12]; }
 type rfcomm >/dev/null 2>&1 || { unset TYPES[11]; unset TYPES[10]; unset TYPES[9]; }
 type irdadump >/dev/null 2>&1 || { unset TYPES[8]; unset TYPES[7]; unset TYPES[6]; }
 
 # man irattach
-DONGLES=(auto "$SIR" on \
-act200l "ACTiSYS Ir-200L dongles" off \
-actisys "ACTiSYS IR-220L dongle" off \
-actisys+ "ACTiSYS IR-220L+ dongle" off \
-airport "Airport dongle" off \
-ep7211 "IR port driver for the Cirrus Logic EP7211 processor (ARM based)" off \
-esi "Extended Systems JetEye PC ESI-9680" off \
-girbil "Greenwich GIrBIL dongle" off \
-litelink "Parallax LiteLink dongle & Extended Systems JetEye PC ESI-9680B" off \
-old_belkin "Belkin (old) SmartBeam dongle or any dongle only capable of 9600 bauds" off \
-ma600 "Mobile Action ma600 dongles" off \
-mcp2120 "Dongles based on the MCP2120 (Microchip)" off \
-tekram "Tekram IrMate IR-210B dongle" off)
+DONGLES=(
+	"auto $(gettext "Standard SIR (or USB)")" \
+	"act200l ACTiSYS Ir-200L dongles" \
+	"actisys ACTiSYS IR-220L dongle" \
+	"actisys+ ACTiSYS IR-220L+ dongle" \
+	"airport Airport dongle" \
+	"ep7211 IR port driver for the Cirrus Logic EP7211 processor (ARM based)" \
+	"esi Extended Systems JetEye PC ESI-9680" \
+	"girbil Greenwich GIrBIL dongle" \
+	"litelink Parallax LiteLink dongle & Extended Systems JetEye PC ESI-9680B" \
+	"old_belkin Belkin (old) SmartBeam dongle or any dongle only capable of 9600 bauds" \
+	"ma600 Mobile Action ma600 dongles" \
+	"mcp2120 Dongles based on the MCP2120 (Microchip)" \
+	"tekram Tekram IrMate IR-210B dongle"
+)
 
-AUTODEVICE=(auto "$AUTOSEARCH" off)
+AUTODEVICE=(
+	"auto $(gettext "scan ALL devices")"
+)
 
-SERIALDEVICES=(ttyS0 "(COM1:)" off \
-ttyS1 "(COM2:)" off \
-ttyS2 "(COM3:)" off \
-ttyS3 "(COM4:)" off \
-ttyS4 "(COM5:)" off \
-ttyS5 "(COM6:)" off \
-ttyS6 "(COM7:)" off \
-ttyS7 "(COM8:)" off \
-ttyS8 "(COM9:)" off \
-ttyS9 "(COM10:)" off \
-ttyS10 "(COM11:)" off \
-ttyS11 "(COM12:)" off \
-ttyS12 "(COM13:)" off \
-ttyS13 "(COM14:)" off \
-ttyS14 "(COM15:)" off \
-ttyS15 "(COM16:)" off)
+SERIALDEVICES=(
+	"ttyS0 (COM1:)" \
+	"ttyS1 (COM2:)" \
+	"ttyS2 (COM3:)" \
+	"ttyS3 (COM4:)" \
+	"ttyS4 (COM5:)" \
+	"ttyS5 (COM6:)" \
+	"ttyS6 (COM7:)" \
+	"ttyS7 (COM8:)" \
+	"ttyS8 (COM9:)" \
+	"ttyS9 (COM10:)" \
+	"ttyS10 (COM11:)" \
+	"ttyS11 (COM12:)" \
+	"ttyS12 (COM13:)" \
+	"ttyS13 (COM14:)" \
+	"ttyS14 (COM15:)" \
+	"ttyS15 (COM16:)"
+)
 
-USBDEVICES=(ttyACM0 "USB Modem 1" off \
-ttyACM1 "USB Modem 2" off \
-ttyACM2 "USB Modem 3" off \
-ttyACM3 "USB Modem 4" off \
-ttyUSB0 "USB Serial 0" off \
-ttyUSB1 "USB Serial 1" off \
-ttyUSB2 "USB Serial 2" off \
-ttyUSB3 "USB Serial 3" off)
+USBDEVICES=(
+	"ttyACM0 USB Modem 1" \
+	"ttyACM1 USB Modem 2" \
+	"ttyACM2 USB Modem 3" \
+	"ttyACM3 USB Modem 4" \
+	"ttyUSB0 USB Serial 0" \
+	"ttyUSB1 USB Serial 1" \
+	"ttyUSB2 USB Serial 2" \
+	"ttyUSB3 USB Serial 3"
+)
 
 num=${#COMMANDS[@]}
 
 gauge() {
 	rm -f "$TMP.done"
 	status=0
-	while [ ! -e "$TMP.done" ]; do echo "$status" ; status="`expr \( 100 - $status \) / 4 + $status`"; sleep 2; done | $DIALOG --title "$TITLE_GAUGE" --gauge "$1" 8 75 0
+	while [ ! -e "$TMP.done" ]; do
+		printf "$status\n"
+		printf "$1\n"
+		status="$(expr \( 100 - $status \) / 4 + $status)"
+		sleep 2
+	done | ssft_progress_bar "$(gettext "Scanning devices...")"
 }
 
 # Stop status bar
@@ -154,47 +130,41 @@ killgauge() {
 }
 
 conntype() {
-	rm -f "$TMP"
-	$DIALOG --clear --title "$TITLE1" --radiolist "$MESSAGE1" 18 75 9 "${TYPES[@]}" 2>"$TMP" || bailout 1
-	read TYPE <"$TMP"
-	TYPE="${TYPE#\"}"; TYPE="${TYPE%\"}"
-	rm -f "$TMP"
+	SSFT_DEFAULT="${TYPES[0]}"
+	ssft_select_single "$(gettext "Connection Type")" "$(gettext "Please select type of connection:")" "${TYPES[@]}"  || bailout 1
+	[ -n "$SSFT_RESULT" ] && TYPE=$(echo $SSFT_RESULT | cut -d" " -f1)
+	unset SSFT_DEFAULT
+
 	return 0
 }
 
 startservice() {
 	case "$TYPE" in
 		serial)
-			rm -f "$TMP"
-			$DIALOG --clear --title "$TITLE_RAWDEVICE" --radiolist "$MESSAGE_RAWDEVICE" 18 75 9 "${SERIALDEVICES[@]}" 2>"$TMP" || bailout 1
-			read DEVICE <"$TMP"
-			DEVICE="${DEVICE#\"}"; DEVICE="${DEVICE%\"}"
-			rm -f "$TMP"
+			ssft_select_single "$(gettext "DEVICE")" "$(gettext "Please select")" "${SERIALDEVICES[@]}"  || bailout 1
+			[ -n "$SSFT_RESULT" ] && DEVICE=$(echo $SSFT_RESULT | cut -d" " -f1)
 			;;
 		winmodem)
 			[ -n "$DISPLAY" ] && x-terminal-emulator -e bash -c "scanmodem; read -p 'Enter to quit.'" || { scanmodem; read -p 'Enter to quit.'; }
 			return 1
 			;;
 		usb)
-			rm -f "$TMP"
-			$DIALOG --clear --title "$TITLE_RAWDEVICE" --radiolist "$MESSAGE_RAWDEVICE" 18 75 9 "${USBDEVICES[@]}" 2>"$TMP" || bailout 1
-			read DEVICE <"$TMP"
-			DEVICE="${DEVICE#\"}"; DEVICE="${DEVICE%\"}"
-			rm -f "$TMP"
+			ssft_select_single "$(gettext "DEVICE")" "$(gettext "Please select")" "${USBDEVICES[@]}"  || bailout 1
+			[ -n "$SSFT_RESULT" ] && DEVICE=$(echo $SSFT_RESULT | cut -d" " -f1)
 			;;
 		irda)
 			killall irattach 2>/dev/null
 			modprobe irda 2>/dev/null
 			modprobe ircomm-tty 2>/dev/null
-			rm -f "$TMP"
-			$DIALOG --clear --title "$TITLE_RAWDEVICE" --radiolist "$MESSAGE_RAWDEVICE" 18 75 9 "${AUTODEVICE[@]}" "${SERIALDEVICES[@]}" "${USBDEVICES[@]}" 2>"$TMP" || bailout 1
-			read RAWDEVICE <"$TMP"
-			RAWDEVICE="${RAWDEVICE#\"}"; RAWDEVICE="${RAWDEVICE%\"}"
-			rm -f "$TMP"
-			$DIALOG --clear --title "$TITLE_DONGLES" --radiolist "$MESSAGE_DONGLES" 18 75 9 "${DONGLES[@]}" 2>"$TMP" || bailout 1
-			read DONGLE <"$TMP"
-			DONGLE="${DONGLE#\"}"; DONGLE="${DONGLE%\"}"
-			rm -f "$TMP"
+
+			ssft_select_single "$(gettext "DEVICE")" "$(gettext "Please select")" "${AUTODEVICE[@]}" "${SERIALDEVICES[@]}" "${USBDEVICES[@]}"  || bailout 1
+			[ -n "$SSFT_RESULT" ] && RAWDEVICE=$(echo $SSFT_RESULT | cut -d" " -f1)
+
+			SSFT_DEFAULT="${DONGLES[0]}"
+			ssft_select_single "$(gettext "IRDA Adapter type")" "$(gettext "Please select type of IRDA adapter:")" "${DONGLES[@]}"  || bailout 1
+			[ -n "$SSFT_RESULT" ] && DONGLE=$(echo $SSFT_RESULT | cut -d" " -f1)
+			unset SSFT_DEFAULT
+
 			case "$DONGLE" in auto) DONGLE="" ;; *) DONGLE="-d $DONGLE" ;; esac
 			if [ "$RAWDEVICE" = "auto" ]; then
 				gauge "Device-Scan..." &
@@ -217,7 +187,8 @@ startservice() {
 			if ifconfig irda0 >/dev/null 2>&1; then
 				true
 			else
-				$DIALOG --clear --title "$TITLE_SRVFAIL" --msgbox "$MESSAGE_SRVFAIL" 18 75
+
+				ssft_display_message "$(gettext "ERROR")" "$(gettext "Failed to start device daemon. Probably the selected port is wrong.")"
 				DEVICE=""
 				return 1
 			fi
@@ -246,13 +217,8 @@ startservice() {
 			gauge "Device-Scan..." &
 			
 			while read HW NAME; do
-				d0="$(($count * 3))"
-				d1="$(($count * 3 + 1))"
-				d2="$(($count * 3 + 2))"
 
-				BLUES[$d0]="$HW"
-				BLUES[$d1]="$NAME"
-				BLUES[$d2]="off"
+				[ -n "$HW" ] && BLUES[$count]="${HW}--${NAME}"
 
 				count=$(($count + 1))
 			done <<EOT
@@ -261,28 +227,35 @@ EOT
 			killgauge
 			
 			if [ -n "${BLUES[0]}" ]; then
-				$DIALOG --clear --title "$TITLE_BLUES" --radiolist "$MESSAGE_BLUES" 18 75 9 "${BLUES[@]}" 2>"$TMP" || bailout 1
+
+				ssft_select_single "$(gettext "Bluetooth Devices")" "$(gettext "These bluetooth devices exist nearby. Please select:")" "${BLUES[@]}"  || bailout 1
+				[ -n "$SSFT_RESULT" ] && RAWDEVICE=$(echo $SSFT_RESULT | cut -d\- -f1)
 			else
-				$DIALOG --title "$TITLE_BTID" --inputbox "$MESSAGE_BTID" 15 60 "00:00:00:00:00:00" 2>"$TMP" || bailout 1
+				SSFT_DEFAULT="00:00:00:00:00:00"
+				ssft_read_string \
+					"$(gettext "No bluetooth devices in range")" \
+					"$(gettext "No bluetooth devices responded to our scan. Please enter the address of a remote bluetooth device.")" \
+					|| bailout 1
+				unset SSFT_DEFAULT
+				[ -n "$SSFT_RESULT" ] && RAWDEVICE="$SSFT_RESULT"
 			fi
 
-			read RAWDEVICE <"$TMP"
-			RAWDEVICE="${RAWDEVICE#\"}"; RAWDEVICE="${RAWDEVICE%\"}"
-			rm -f "$TMP"
 			
 			if [ -r /etc/bluetooth/pin ]; then
 				read PIN < /etc/bluetooth/pin  2>/dev/null
 				rm -f "$TMP"
 			fi
 
-			if [ -n "$DISPLAY" ]; then
-				$DIALOG --title "$TITLE_PIN" --inputbox "$MESSAGE_PIN" 8 65 "$PIN" 2>"$TMP" || bailout 1
-			fi
 
-			read PIN <"$TMP" 2>/dev/null
-			rm -f	"$TMP" \
-				/etc/bluetooth/pin
+			SSFT_DEFAULT="$PIN"
+			ssft_read_string \
+				"$(gettext "PIN")" \
+				"$(gettext "Please chose a 4-digit PIN number for authention of bluetooth devices:")" \
+				|| bailout 1
+			unset SSFT_DEFAULT
+			[ -n "$SSFT_RESULT" ] && PIN="$SSFT_RESULT"
 
+			rm -f /etc/bluetooth/pin
 			echo "$PIN" >/etc/bluetooth/pin
 
 			rm -f /etc/bluetooth/rfcomm.conf
@@ -323,12 +296,16 @@ while true; do
 	startservice
 	
 	if [ "$?" = "0" -a -n "$DEVICE" ]; then
-		$DIALOG --title "$TITLE_LINK" --yesno "$MESSAGE_LINK $DEVICE ?" 15 65 || bailout 1
+
+		ssft_yesno "$(gettext "Create /dev/modem link...")" "$(eval_gettext "Do you want to set the symlink /dev/modem to point to the newly configured device? This is necessary if you want o use the device as modem for kppp, as an example, or for using GPRS (all of these located in the sidux \"network configuration\" menu).
+
+Create link /dev/modem ->  \$DEVICE ?")" || bailout 1
+
 		rm -f /dev/modem
 		ln -sf /dev/"$DEVICE" /dev/modem
 		break
 	else
-		$DIALOG --clear --title "$TITLE_RETRY" --yesno "$MESSAGE_RETRY" 18 75 || bailout 1
+		ssft_yesno "$(gettext "ERROR")" "$(gettext "This seems to have failed. Do you want to try again?")"  || bailout 1
 	fi
 done
 
